# Generated by Django 5.1.3 on 2024-11-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To do', 'To do'), ('In Progress', 'In Progress'), ('Need Review', 'Need Review'), ('Done', 'Done')], default='To do', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=100),
        ),
    ]
