# Generated by Django 5.1.3 on 2024-12-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_status_alter_task_priority'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='substatus',
            field=models.CharField(choices=[('Not started', 'Not started'), ('In Research', 'In Research'), ('On Track', 'On Track'), ('Completed', 'Completed')], default='Not started', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='team_members',
            field=models.ManyToManyField(related_name='assigned_tasks', to='users.user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(verbose_name='Due Date'),
        ),
    ]
